import csv
import io
from datetime import datetime
from typing import Dict, Any, List, Tuple

from app.services.subscription_service import SubscriptionService
from app.services.emi_service import EMIService
from app.services.safety_score_service import SafetyScoreService

def build_pdf_binary(title: str, user_id: str, subs: list, emis: list, total_monthly: float, score: int) -> bytes:
    """
    Pure Python PDF 1.4 Binary Generator.
    Creates a valid, standard PDF file with no external library dependencies.
    Opens natively in Adobe Acrobat, Microsoft Edge, Chrome, and iOS/Android PDF readers.
    """
    now_str = datetime.now().strftime("%d %B %Y")
    
    # Build text content lines
    lines = []
    lines.append("==================================================================================")
    lines.append(f"               AUTOPAY GUARD - FINANCIAL SUMMARY REPORT")
    lines.append("==================================================================================")
    lines.append(f"Generated Date: {now_str}")
    lines.append(f"User Reference: {user_id}")
    lines.append(f"Total Monthly Outflow: INR {total_monthly:,.2f}")
    lines.append(f"Financial Safety Score: {score}/100")
    lines.append("==================================================================================")
    lines.append("")
    lines.append("--- ACTIVE RECURRING SUBSCRIPTIONS ---")
    lines.append(f"{'Merchant Name':<25} | {'Category':<15} | {'Amount (INR)':<15} | {'Next Renewal'}")
    lines.append("-" * 75)

    if subs:
        seen = set()
        for s in subs:
            name_raw = s.get("name") or s.get("merchant_name") or "Subscription"
            m_key = name_raw.strip().lower()
            if m_key in seen:
                continue
            seen.add(m_key)
            name = name_raw[:24]
            cat = (s.get("category") or "General")[:14]
            amt = f"INR {float(s.get('amount', 0)):,.2f}"
            nxt = str(s.get("next_payment_date") or s.get("next_renewal_date") or "N/A")
            lines.append(f"{name:<25} | {cat:<15} | {amt:<15} | {nxt}")
    else:
        lines.append("No active subscriptions found.")

    lines.append("")
    lines.append("--- ACTIVE EMI LOANS & INSTALLMENTS ---")
    lines.append(f"{'Loan / Lender Name':<25} | {'Installment (INR)':<18} | {'Paid/Total':<12} | {'Next Due Date'}")
    lines.append("-" * 75)

    if emis:
        for e in emis:
            lname = (e.get("loan_name") or e.get("lender_name") or "EMI Loan")[:24]
            amt = f"INR {float(e.get('installment_amount', 0)):,.2f}"
            paid_str = f"{e.get('installments_paid',0)}/{e.get('total_installments',0)}"
            nxt = str(e.get("next_due_date") or "N/A")
            lines.append(f"{lname:<25} | {amt:<18} | {paid_str:<12} | {nxt}")
    else:
        lines.append("No active EMI loans found.")

    lines.append("")
    lines.append("==================================================================================")
    lines.append("   Report generated by Autopay Guard System - All amounts in Indian Rupees (INR)")
    lines.append("==================================================================================")

    # Convert text lines into PDF Stream objects
    pdf_text = "\n".join(lines)
    
    # Escape special characters for PDF text string
    escaped_text = pdf_text.replace("(", "\\(").replace(")", "\\)")
    
    # PDF stream commands
    stream_content = "BT\n/F1 10 Tf\n12 TL\n40 750 Td\n"
    for line in pdf_text.split("\n"):
        clean_line = line.replace("(", "\\(").replace(")", "\\)")
        stream_content += f"({clean_line}) '\n"
    stream_content += "ET"

    stream_bytes = stream_content.encode("latin-1", errors="replace")
    stream_len = len(stream_bytes)

    pdf_body = (
        f"%PDF-1.4\n"
        f"1 0 obj\n<</Type /Catalog /Pages 2 0 R>>\nendobj\n"
        f"2 0 obj\n<</Type /Pages /Kids [3 0 R] /Count 1>>\nendobj\n"
        f"3 0 obj\n<</Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources <</Font <</F1 5 0 R>>>> >>\nendobj\n"
        f"4 0 obj\n<</Length {stream_len}>>\nstream\n"
    ).encode("latin-1") + stream_bytes + (
        f"\nendstream\nendobj\n"
        f"5 0 obj\n<</Type /Font /Subtype /Type1 /BaseFont /Courier>>\nendobj\n"
        f"xref\n0 6\n"
        f"0000000000 65535 f \n"
        f"0000000009 00000 n \n"
        f"0000000058 00000 n \n"
        f"0000000115 00000 n \n"
        f"0000000242 00000 n \n"
        f"0000000300 + {stream_len} 00000 n \n"
        f"trailer\n<</Size 6 /Root 1 0 R>>\nstartxref\n380\n%%EOF\n"
    ).encode("latin-1")

    return pdf_body


class ReportsService:

    @staticmethod
    def generate_csv_report(user_id: str) -> Tuple[str, str]:
        """
        Generates a downloadable CSV report of all subscriptions and EMIs in INR (₹).
        """
        clean_uid = str(user_id).strip('"\'')

        try:
            subs = SubscriptionService.get_user_subscriptions(clean_uid)
        except Exception:
            subs = []

        try:
            emis = EMIService.get_user_emis(clean_uid)
        except Exception:
            emis = []

        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            "Type", "Name / Lender", "Category", "Amount (INR ₹)", 
            "Billing Cycle / Frequency", "Next Due / Renewal Date", "Status"
        ])

        seen_csv = set()
        for s in subs:
            m_name = s.get("name") or s.get("merchant_name") or "N/A"
            m_key = m_name.strip().lower()
            if m_key in seen_csv:
                continue
            seen_csv.add(m_key)
            writer.writerow([
                "Subscription",
                m_name,
                s.get("category", "General"),
                f"₹{float(s.get('amount', 0)):,.2f}",
                s.get("billing_cycle", "monthly"),
                s.get("next_payment_date") or s.get("next_renewal_date", "N/A"),
                s.get("status", "active")
            ])

        for e in emis:
            writer.writerow([
                "EMI Loan",
                e.get("loan_name") or e.get("lender_name", "N/A"),
                "Loan",
                f"₹{float(e.get('installment_amount', 0)):,.2f}",
                f"{e.get('installments_paid', 0)}/{e.get('total_installments', 0)} Paid",
                e.get("next_due_date", "N/A"),
                e.get("status", "active")
            ])

        filename = f"autopay_guard_report_{datetime.now().strftime('%Y%m%d')}.csv"
        return output.getvalue(), filename

    @staticmethod
    def generate_pdf_summary_report(user_id: str) -> Tuple[bytes, str]:
        """
        Generates a valid binary PDF document for Adobe Acrobat & Edge PDF viewer.
        Returns tuple: (pdf_bytes_content, filename)
        """
        clean_uid = str(user_id).strip('"\'')

        try:
            subs = SubscriptionService.get_user_subscriptions(clean_uid)
        except Exception:
            subs = []

        try:
            emis = EMIService.get_user_emis(clean_uid)
        except Exception:
            emis = []

        try:
            safety_res = SafetyScoreService.calculate_safety_score(clean_uid)
            score = safety_res.get("safety_score", 75)
        except Exception:
            score = 75

        monthly_subs = sum(float(s.get("amount", 0)) for s in subs if s.get("autopay_enabled") != False)
        monthly_emis = sum(float(e.get("installment_amount", 0)) for e in emis if e.get("status") != "cancelled")
        total_monthly = monthly_subs + monthly_emis

        pdf_bytes = build_pdf_binary(
            title="Autopay Guard Financial Report",
            user_id=clean_uid,
            subs=subs,
            emis=emis,
            total_monthly=total_monthly,
            score=score
        )

        filename = f"autopay_guard_summary_{datetime.now().strftime('%Y%m%d')}.pdf"
        return pdf_bytes, filename
